import random


def rand(options):
    return random.choice(options)


def pairs_with():
    return rand([
        "allspice",
        "anise",
        "bananas",
        "bank holidays",
        "barbecue",
        "birthday cake",
        "black pepper",
        "brown salads",
        "cake",
        "cheap pasties",
        "cheese",
        "chicken",
        "chickens",
        "chili pepper",
        "cinnamon",
        "coq au vin",
        "crab & lobster",
        "cream pasta with chicken",
        "cream sauce",
        "cumin",
        "danger",
        "dispair",
        "easter eggs",
        "fennel",
        "fried chicken",
        "greek food",
        "green salads",
        "hamburgers",
        "hard cheeses",
        "hearty vegetable soups",
        "ice cream",
        "indian cuisine",
        "ketchup",
        "lasagna",
        "lebanese cuisine",
        "lilac salads",
        "Mexican foods",
        "more wine",
        "mushroom risotto",
        "orange salads",
        "pesto",
        "pink salads",
        "pizza",
        "pungent cheeses",
        "Red Bull",
        "red meat",
        "roast pork",
        "roasted vegetables",
        "rosemary",
        "sausage rolls",
        "savory mushroom dishes",
        "smoked meats",
        "soft cheeses",
        "storm clouds",
        "sushi",
        "tarragon chicekn",
        "thai food",
        "turkish food",
        "vodka",
    ])


def style():
    return rand([
        "aggressive",
        "alcoholic",
        "balanced",
        "baroque",
        "bitter",
        "brutal",
        "clammy",
        "clean",
        "complex",
        "conniving",
        "crisp",
        "crispy",
        "deceptive",
        "delightfully alcoholic",
        "dirty",
        "disheveled",
        "dry",
        "earthy",
        "full-bodied",
        "grape-flavoured",
        "harmonious",
        "hypnotic",
        "judgmental",
        "kinky",
        "layered",
        "lingering",
        "lurking",
        "muddy",
        "nicely integrated",
        "ominous",
        "overrated",
        "resentful",
        "rich",
        "ripe",
        "sweaty",
        "swift",
        "tart",
        "turgid",
        "unbalanced",
        "unstructured",
        "wet",
        "wine-like",
    ])


def wine_type():
    return rand([
        "Cabernet Sauvignon",
        "Chardonnay",
        "Malbec",
        "Merlot",
        "Monastrell",
        "Petit Sirah",
        "Pinot Gris",
        "Pinot Noir",
        "Pinotage",
        "Riesling",
        "Rosé",
        "Sauvignon Blanc",
        "Schiava",
        "Sémillon",
        "Shiraz",
        "Syrah",
        "Viognier",
        "Zinfandel",
    ])


def hints():
    return rand([
        "a whiff",
        "bits",
        "evidence",
        "hints",
        "implications",
        "inklings",
        "memories",
        "mentions",
        "notes",
        "signs",
        "suggestions",
        "suspicions",
        "tinges",
        "traces",
        "whispers",
    ])


def note():
    return rand([
        "apple",
        "bacon",
        "baked potatoes",
        "beans",
        "black current",
        "blackberry",
        "bleach",
        "blueberry",
        "brick",
        "butter",
        "camomile",
        "caramel",
        "chalk",
        "Chewits®",
        "chlorine",
        "cigars",
        "coffee",
        "cola",
        "citrus",
        "durian",
        "drains",
        "elderflower",
        "fags",
        "fennel",
        "floral aromatics",
        "hibiscus",
        "hot cross buns",
        "lavendar",
        "lutefisk",
        "lychee",
        "miso",
        "noodles",
        "olive",
        "passion fruit",
        "peat",
        "plum",
        "poptarts",
        "pub floor",
        "rhubarb",
        "sashimi",
        "slate",
        "soy sauce",
        "spices",
        "summer fruits",
        "surströmming",
        "toast",
        "tobacco",
        "vanilla",
        "velvet",
    ])


def smell():
    return rand([
        "a both good and bad",
        "a darkly humerous",
        "a dense, almost foggy",
        "a frankly misleading",
        "a gloomily tainted",
        "a mischievous",
        "a mysterious",
        "a sickeningly sweet",
        "a somehow smug",
        "a somewhat sickening",
        "a subtly vinegary",
        "a surprisingly erotic",
        "a thick, secretive",
        "a thoroughly unpleasant",
        "a tough",
        "a turbulent",
        "a twisted",
        "an exaustingly energetic",
        "an exuberant",
        "an honestly quite unnerving",
        "an optimistically old-fashioned",
        "an overbearing",
        "an uninviting",
    ])


def sentence():
    return " ".join([
        "This",
        style(),
        "and",
        style(),
        wine_type(),
        "has",
        hints(),
        "of",
        note(),
        "and",
        note() + ",",
        "with",
        smell(),
        rand([
            "aroma",
            "smell",
            "texture",
            "appearance",
        ]) + ".",
        "Pairs well with",
        pairs_with(),
        "or",
        pairs_with(),
    ]) + "."
